steps:
  - name: ":eslint: Lint"
    command: "npm install & npm run lint"
    plugins:
      - docker#v3.8.0:
          image: "node:latest"
          always-pull: true

  - wait

  - name: ":jest: Test"
    command: "npm run test"
    agents:
      queue: default