steps:
  - name: ":eslint: Lint"
    command: "npm install & npm run lint"
    agents:
      queue: default

  - wait

  - name: ":jest: Test"
    command: "npm run test"
    agents:
      queue: default